# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UICollectionView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Masonry', '~> 1.1.0'

  # Pods for UICollectionView

  target 'UICollectionViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UICollectionViewUITests' do
    # Pods for testing
  end

end
